import { Subscription, CancelledSubscription } from '@/types/subscription';

// Popular Indian subscription platforms with dummy data
export const DUMMY_SUBSCRIPTIONS: Subscription[] = [
  {
    id: '1',
    name: 'Netflix Premium',
    logo: 'netflix',
    category: 'Entertainment',
    amount: 649,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-15',
    paymentMethod: 'UPI',
    status: 'active',
    startDate: '2024-01-15',
    usageScore: 85,
    hoursUsed: 30,
    lastUsed: '2025-01-08',
    autoRenewal: true,
    reminder: true,
  },
  {
    id: '2',
    name: 'Amazon Prime',
    logo: 'amazonprime',
    category: 'Entertainment',
    amount: 1499,
    currency: '₹',
    billingCycle: 'yearly',
    nextBilling: '2025-12-20',
    paymentMethod: 'Credit Card',
    status: 'active',
    startDate: '2024-01-20',
    usageScore: 92,
    autoRenewal: true,
    reminder: true,
  },
  {
    id: '3',
    name: 'Spotify Premium',
    logo: 'spotify',
    category: 'Music',
    amount: 119,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-10',
    paymentMethod: 'UPI',
    status: 'active',
    startDate: '2024-03-10',
    usageScore: 78,
    hoursUsed: 45,
    lastUsed: '2025-01-09',
    autoRenewal: true,
    reminder: false,
  },
  {
    id: '4',
    name: 'Disney+ Hotstar',
    logo: 'disneyhotstar',
    category: 'Entertainment',
    amount: 499,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-18',
    paymentMethod: 'UPI',
    status: 'active',
    startDate: '2024-02-18',
    usageScore: 45,
    hoursUsed: 8,
    lastUsed: '2024-12-20',
    autoRenewal: true,
    reminder: true,
  },
  {
    id: '5',
    name: 'YouTube Premium',
    logo: 'youtubepremium',
    category: 'Entertainment',
    amount: 129,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-12',
    paymentMethod: 'UPI',
    status: 'active',
    startDate: '2024-04-12',
    usageScore: 95,
    hoursUsed: 60,
    lastUsed: '2025-01-10',
    autoRenewal: true,
    reminder: false,
  },
  {
    id: '6',
    name: 'Zerodha Streak',
    logo: 'zerodhastreak',
    category: 'Finance',
    amount: 499,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-20',
    paymentMethod: 'Auto Debit',
    status: 'active',
    startDate: '2024-05-20',
    usageScore: 68,
    autoRenewal: true,
    reminder: true,
  },
  {
    id: '7',
    name: 'Swiggy One',
    logo: 'swiggyone',
    category: 'Food',
    amount: 149,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-14',
    paymentMethod: 'UPI',
    status: 'active',
    startDate: '2024-06-14',
    usageScore: 55,
    autoRenewal: true,
    reminder: false,
  },
  {
    id: '8',
    name: 'Google One',
    logo: 'googleone',
    category: 'Cloud Storage',
    amount: 130,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-25',
    paymentMethod: 'Credit Card',
    status: 'active',
    startDate: '2024-07-25',
    usageScore: 88,
    autoRenewal: true,
    reminder: false,
  },
  {
    id: '9',
    name: 'Zee5 Premium',
    logo: 'zee5premium',
    category: 'Entertainment',
    amount: 299,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-22',
    paymentMethod: 'UPI',
    status: 'active',
    startDate: '2024-08-22',
    usageScore: 32,
    hoursUsed: 4,
    lastUsed: '2024-12-15',
    autoRenewal: true,
    reminder: true,
  },
  {
    id: '10',
    name: 'Cult.fit',
    logo: 'cultfit',
    category: 'Fitness',
    amount: 1200,
    currency: '₹',
    billingCycle: 'quarterly',
    nextBilling: '2025-02-10',
    paymentMethod: 'Credit Card',
    status: 'active',
    startDate: '2024-05-10',
    usageScore: 72,
    autoRenewal: true,
    reminder: true,
  },
  {
    id: '11',
    name: 'Audible',
    logo: 'audible',
    category: 'Education',
    amount: 199,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-16',
    paymentMethod: 'Credit Card',
    status: 'active',
    startDate: '2024-09-16',
    usageScore: 64,
    autoRenewal: true,
    reminder: false,
  },
  {
    id: '12',
    name: 'LinkedIn Premium',
    logo: 'linkedinpremium',
    category: 'Productivity',
    amount: 1699,
    currency: '₹',
    billingCycle: 'monthly',
    nextBilling: '2025-01-28',
    paymentMethod: 'Credit Card',
    status: 'active',
    startDate: '2024-10-28',
    usageScore: 58,
    autoRenewal: true,
    reminder: true,
  },
];

export const CANCELLED_SUBSCRIPTIONS: CancelledSubscription[] = [
  {
    id: 'c1',
    name: 'Disney+ Hotstar',
    logo: 'disneyhotstar',
    category: 'Entertainment',
    amount: 499,
    currency: '₹',
    billingCycle: 'monthly',
    paymentMethod: 'UPI',
    startDate: '2023-08-15',
    cancelledDate: '2024-10-15',
    reason: 'Not watching IPL anymore',
    savedAmount: 1497,
    monthsCancelled: 3,
  },
  {
    id: 'c2',
    name: 'Swiggy One',
    logo: 'swiggyone',
    category: 'Food',
    amount: 149,
    currency: '₹',
    billingCycle: 'monthly',
    paymentMethod: 'UPI',
    startDate: '2023-05-20',
    cancelledDate: '2024-08-20',
    reason: 'Cooking at home more often',
    savedAmount: 745,
    monthsCancelled: 5,
  },
  {
    id: 'c3',
    name: 'Zee5 Premium',
    logo: 'zee5premium',
    category: 'Entertainment',
    amount: 999,
    currency: '₹',
    billingCycle: 'yearly',
    paymentMethod: 'Credit Card',
    startDate: '2023-01-10',
    cancelledDate: '2024-05-10',
    reason: 'Content not relevant',
    savedAmount: 7992,
    monthsCancelled: 8,
  },
  {
    id: 'c4',
    name: 'Apple Music',
    logo: 'applemusic',
    category: 'Music',
    amount: 99,
    currency: '₹',
    billingCycle: 'monthly',
    paymentMethod: 'Credit Card',
    startDate: '2023-03-01',
    cancelledDate: '2024-03-01',
    reason: 'Switched to Spotify',
    savedAmount: 990,
    monthsCancelled: 10,
  },
  {
    id: 'c5',
    name: 'SonyLIV',
    logo: 'sonyliv',
    category: 'Entertainment',
    amount: 299,
    currency: '₹',
    billingCycle: 'monthly',
    paymentMethod: 'UPI',
    startDate: '2023-06-15',
    cancelledDate: '2024-09-15',
    reason: 'Too many OTT subscriptions',
    savedAmount: 897,
    monthsCancelled: 3,
  },
  {
    id: 'c6',
    name: 'Gaana Plus',
    logo: 'gaanaplus',
    category: 'Music',
    amount: 299,
    currency: '₹',
    billingCycle: 'yearly',
    paymentMethod: 'UPI',
    startDate: '2022-12-20',
    cancelledDate: '2023-12-20',
    reason: 'Not using enough',
    savedAmount: 299,
    monthsCancelled: 12,
  },
];

// Dummy user data
export const DUMMY_USER = {
  id: '1',
  name: 'Rahul Sharma',
  email: 'user@subtract.com',
  phone: '+91 98765 43210',
  avatar: '/avatars/default.png',
  token: '',
  joinedDate: '2024-01-15',
  preferences: {
    currency: 'INR' as const,
    language: 'en' as const,
    theme: 'dark' as const,
    notifications: {
      email: true,
      push: true,
      sms: false,
      reminderDays: 3,
    },
    budgetAlerts: true,
    weeklyReports: true,
  },
  budget: 5000,
};

// Platform logo identifiers (slug) for quick lookups
export const PLATFORM_LOGOS: Record<string, string> = {
  netflix: 'netflix',
  prime: 'amazonprime',
  'amazon prime': 'amazonprime',
  spotify: 'spotify',
  hotstar: 'disneyhotstar',
  'disney+ hotstar': 'disneyhotstar',
  youtube: 'youtubepremium',
  'youtube premium': 'youtubepremium',
  zerodha: 'zerodhastreak',
  'zerodha streak': 'zerodhastreak',
  swiggy: 'swiggyone',
  'swiggy one': 'swiggyone',
  'google one': 'googleone',
  zee5: 'zee5premium',
  'zee5 premium': 'zee5premium',
  cultfit: 'cultfit',
  'cult.fit': 'cultfit',
  audible: 'audible',
  linkedin: 'linkedinpremium',
  'linkedin premium': 'linkedinpremium',
  apple: 'applemusic',
  'apple music': 'applemusic',
  sonyliv: 'sonyliv',
  gaana: 'gaanaplus',
  'gaana plus': 'gaanaplus',
};
